name: hakot_driver_app
description: "SmartTrashRoute - Hakot Drivers App."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2  # Adjusted to match your current Dart SDK version

dependencies:
  flutter:
    sdk: flutter

  # Device preview & UI packages
  device_preview: ^1.2.0
  cupertino_icons: ^1.0.8
  bcrypt: ^1.1.3
  shared_preferences: ^2.0.15
  http: ^1.3.0
  geolocator: ^9.0.2
  cached_network_image: ^3.2.3
  flutter_background: ^1.0.8
  connectivity_plus: ^6.1.3

  # Map & location packages
  flutter_map: ^6.0.0
  latlong2: ^0.9.1

  # Firebase packages
  firebase_core: ^2.27.2
  firebase_database: ^10.5.7

  # Image & Cloudinary packages
  image_picker: ^0.8.7+4
  cloudinary_public: ^0.23.1

  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Hakot.png
    - assets/images/Cenro.png
    - assets/images/TagumCity.png
    - assets/images/UMLogo.png
    - assets/images/Google.png
    - assets/images/ChangePass.png
    - assets/images/Verify.png
    - assets/images/ForgotPass.png
    - assets/images/profile-picture.png
    - assets/images/hakot_2.png
    - assets/images/garbage-truck.png
    - assets/images/sewage-truck.png
